Add an introduction to utility function NewJSONReader in USER_GUIDE
opensearch-project/opensearch-go pull request #341
Opened 2023-06-28 01:38 UTC by YuyaAbo

### Description

There is a common case where a structure is used in the Body of an API request, which requires conversion to io.Reader. There is a useful utility function available for this use case, but it is not often noticed, so it is included in the user guide.

ref. https://github.com/opensearch-project/opensearch-go/issues/331#issuecomment-1608111897

### Issues Resolved

There is no Issue to be resolved, but the related Issue is https://github.com/opensearch-project/opensearch-go/issues/331

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-06-28 20:39 UTC, dblock requested changes
Thank you! Fix formatting and we're good to go?

2023-06-28 20:39 UTC, dblock commented on USER_GUIDE.md
> +    }{
Looks like some tabs/spaces formatting broken here.

2023-06-29 23:25 UTC, YuyaAbo commented on USER_GUIDE.md
> +    }{
Fixed https://github.com/opensearch-project/opensearch-go/pull/341/commits/e1e12f6c616efc5e1c46594ba91dfab18b0c13ea

2023-06-30 17:22 UTC, dblock approved these changes

2023-06-30 17:22 UTC, merged