Add the Explanation field containing the document explain details to SearchHit
opensearch-project/opensearch-go pull request #504
Opened 2024-04-02 22:52 UTC by zr-bennettm

### Description
Previously, calling the `Search` function [here](https://github.com/opensearch-project/opensearch-go/blob/e0278abbe00fb090faba23170d2a1aac491d6d22/opensearchapi/api_search.go#L21) with `Explain` set to true in `Params` in the `SearchReq` did **not** add an explanation payload to each document. This pull request fixes that by adding an `Explanation` field to the `SearchHit` struct.

### Issues Resolved
This resolves issue [503](https://github.com/opensearch-project/opensearch-go/issues/503),  which I raised.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-03 08:12 UTC, Jakob3xD commented
Thank you for the PR. Looks good so far.
Could you please add a test for this in file `opensearchapi/api_search_test.go`.

You can run the tests locally by following the steps in the [developer guide](https://github.com/opensearch-project/opensearch-go/blob/main/DEVELOPER_GUIDE.md#execute-integration-tests-from-your-terminal).

2024-04-03 17:10 UTC, zr-bennettm commented
@Jakob3xD just added one

2024-04-03 17:42 UTC, dblock approved these changes

2024-04-03 17:42 UTC, dblock requested changes
@zr-bennettm You will need to sign DCO (`git commit -s --amend` and force push) for all your commits, please.

2024-04-03 17:43 UTC, dblock commented
Looks like https://github.com/opensearch-project/opensearch-go/pull/506 is fixing CI, rebase after that's merged.

2024-04-03 17:51 UTC, Jakob3xD requested changes
Small nit but looks good.

2024-04-03 17:51 UTC, Jakob3xD commented on opensearchapi/api_search_test.go
> +		resp, err := client.Search(nil, &opensearchapi.SearchReq{Indices: []string{index}, Body: strings.NewReader(""), Params: opensearchapi.SearchParams{Explain: &explain}})
```suggestion
		resp, err := client.Search(nil, &opensearchapi.SearchReq{Indices: []string{index}, Body: strings.NewReader(""), Params: opensearchapi.SearchParams{Explain: opensearchapi.ToPointer(true)}})
```

2024-04-03 17:55 UTC, zr-bennettm commented
@Jakob3xD @dblock just rebased and went with @Jakob3xD 's suggestion

2024-04-03 18:00 UTC, Jakob3xD approved these changes

2024-04-03 18:28 UTC, dblock approved these changes

2024-04-03 18:28 UTC, merged

2024-04-04 20:40 UTC, zr-bennettm commented
@dblock @Jakob3xD just curious, how long should it take to see this be put into effect? I know it's merged in main but the documentation [here](https://pkg.go.dev/github.com/opensearch-project/opensearch-go/v3@v3.1.0/opensearchapi#SearchHit) isn't updated yet. Do we need to wait until V3.2?

2024-04-06 15:28 UTC, dblock commented
We release often. Open an issue like "Release v.Next", if you need a release quickly.