Add missing `search_pipeline` field in `opensearchapi.SearchParams`
opensearch-project/opensearch-go pull request #532
Opened 2024-04-18 16:23 UTC by jackh-ncl

### Description
Added `search_pipeline` field in SearchParams struct.

_Note: I didn't add any tests as I can't see any others there for existing `SearchParam` fields._

#### Context:

With the addition of hybrid search and search pipelines in Opensearch version `2.11`, a new `search_pipeline` parameter exists on the `_search` endpoint ([docs here](https://opensearch.org/docs/latest/search-plugins/search-pipelines/using-search-pipeline/)).

### Issues Resolved
This pull request supports the new search pipelines functionality by allowing users of the library to set the `search_pipeline` parameter via the `SearchParams` struct.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-18 19:14 UTC, dblock commented
We do need tests for existing and new code, can you please add something simple that exercises params, please?

2024-04-19 12:16 UTC, dblock approved these changes
LGTM, @Jakob3xD has a good answer to your question?

2024-04-19 12:16 UTC, dblock commented on opensearchapi/api_search-params_test.go
> +// Licensed to Elasticsearch B.V. under one or more contributor
This is new code, remove the Elasticsearch license grant part, just leave the SPDX one.

2024-04-19 13:44 UTC, dblock submitted a review, later dismissed

2024-04-22 07:15 UTC, Jakob3xD requested changes
LGTM, only thing missing is the build tag for testing.
Afterwards it is good to merge.

2024-04-22 07:15 UTC, Jakob3xD commented on opensearchapi/api_search-params_test.go
> +
```suggestion
// GitHub history for details.
//
//go:build !integration

```

2024-04-22 09:19 UTC, jackh-ncl commented
Thank you 😃

2024-04-22 09:26 UTC, merged