Improves ParseError response when server response is an unknown json
opensearch-project/opensearch-go pull request #592
Opened 2024-07-20 00:33 UTC by imvtsl

### Description
In ParseError, when json response from server is unknown, it used to return a string response (`*fmt.wrapError`). This is now changed to return a StringError struct (`*opensearch.StringError`).  

### Issues Resolved
Closes #582

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-20 14:02 UTC, dblock requested changes
Thank you!

Is this a breaking change for users or can we make this backwards compatible? If yes, it's likely a major version bump that would need to be done in the same PR, and I definitely think it needs an entry in https://github.com/opensearch-project/opensearch-go/blob/main/UPGRADING.md. 

I think we need to document error handling somewhere in USER_GUIDE, including this behavior, maybe you want to start a guide on that or add to existing ones?

2024-07-22 03:57 UTC, imvtsl commented on CHANGELOG.md
> +- Improves ParseError response when server response is an unknown json([#592](https://github.com/opensearch-project/opensearch-go/pull/592))
done.

2024-07-22 08:16 UTC, imvtsl commented
> Is this a breaking change for users or can we make this backwards compatible? If yes, it's likely a major version bump that would need to be done in the same PR, and I definitely think it needs an entry in https://github.com/opensearch-project/opensearch-go/blob/main/UPGRADING.md.
> 
> I think we need to document error handling somewhere in USER_GUIDE, including this behavior, maybe you want to start a guide on that or add to existing ones?


I am attending a triage meeting with opensearch indexing team on Monday to get more insights into error handling. We can work on a guide for error handling after that.

2024-07-22 20:15 UTC, imvtsl commented
@dblock 
I attended the triage meeting with indexing team today. You can find the summary of the discussion [here](https://github.com/opensearch-project/OpenSearch/issues/14805#issuecomment-2243210410).

The fix with Opensearch will likely go in 3.0. Also, we don't have documentation for error responses. I created issues with documentation after discussion in triage meeting today.

For now, I will get started with USER_GUIDE with the changes in this PR and prepare for a release.

2024-07-23 08:48 UTC, imvtsl commented
I added documentation in UPGRADING.md.

I read RELEASING.md. I believe release manager is authorized to perform the release process. Please let me know if any further action is required from my end for the release.

2024-07-23 12:04 UTC, dblock commented
I didn't see an answer on whether there is any way to make this backwards compatible, so I presume not and I am good with this - @Jakob3xD could you also please take a look?

2024-07-23 14:25 UTC, dblock approved these changes

2024-07-23 14:26 UTC, merged

2024-07-23 22:53 UTC, imvtsl commented
@dblock Apologies for the confusion.
I did look into making it backward compatible but couldn't find a reasonable way for doing so.