Execute item failure callback execution on bulk request error
opensearch-project/opensearch-go pull request #627
Opened 2024-10-02 16:07 UTC by kellen-miller

### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-02 16:48 UTC, kellen-miller commented
I ordered the execution of the item failure callback before the execution of the bulk indexers `OnError` callback, but am open to feedback on if that should be reversed. My thought process was that a user of the library may have some code to shutdown/panic their application in the `OnError` callback, which would result in the item `OnFailure` callbacks to not be executed.

2024-10-02 17:35 UTC, dblock approved these changes
Looks good! 

Let's take this opportunity and add a few more tests to cover the edge cases (some may exist)?

- fails only some items and makes sure that `failedItems` is correct 
- checks that OnError is called every time, and only once, if there's at least one failure

2024-10-02 17:37 UTC, dblock requested changes
Actually looking at the code I see https://github.com/opensearch-project/opensearch-go/pull/627/files#diff-84320628b2df1ee872c513a0e5a15df089c6116a5c2b6e8d4d577102e0bcb6c6R526 that calls `onFailure` below if the response is > 201. 

Something seems fishy ...

2024-10-02 17:47 UTC, kellen-miller commented
Correct that second `OnFailure` is called when the entire bulk request doesn't fail. 

But if the whole bulk request errors, for example if the OpenSeach goes down while the request is in flight or the context deadlines, the flush function immediately returns before executing the failure callbacks.

2024-10-02 18:08 UTC, dblock commented
> Correct that `OnFailure` below if the response is > 201 is called when the bulk request is successful and an individual item in the request fails, say OpenSearch had an indexing failure with the item.
> 
> But if the whole bulk request errors, for example if OpenSearch goes down while the request is in flight, or the context deadlines, the flush function returns without executing the item failure callbacks and the workers buffer is cleared. So those items are lost and their callbacks are never executed.

Understood. And just to double-check, we don't call those callbacks twice in the successful response but some failed items case? Add a test for this?

2024-10-02 18:16 UTC, kellen-miller commented
> Understood. And just to double-check, we don't call those callbacks twice in the successful response but some failed items case? Add a test for this?

Yep the failure callback will only be executed once. If the response is successful (the [error here is nil](https://github.com/kellen-miller/opensearch-go/blob/bugfix/execute-item-fail-callbacks-bulk-error/opensearchutil/bulk_indexer.go#L505)), the code in this PR is never hit. 

My unit test I added has a check to make sure that the number of times the callback is what is expected i.e. nothing is called twice.
https://github.com/kellen-miller/opensearch-go/blob/bugfix/execute-item-fail-callbacks-bulk-error/opensearchutil/bulk_indexer_internal_test.go#L833

2024-10-02 19:13 UTC, dblock commented
> > Understood. And just to double-check, we don't call those callbacks twice in the successful response but some failed items case? Add a test for this?
> 
> Yep the failure callback will only be executed once. If the response is successful (the [error here is nil](https://github.com/kellen-miller/opensearch-go/blob/bugfix/execute-item-fail-callbacks-bulk-error/opensearchutil/bulk_indexer.go#L505)), the code in this PR is never hit.
> 
> My unit test I added has a check to make sure that the number of times the failure callback is executed is what is expected i.e. nothing is called twice. https://github.com/kellen-miller/opensearch-go/blob/bugfix/execute-item-fail-callbacks-bulk-error/opensearchutil/bulk_indexer_internal_test.go#L833

I think there's still a test missing for partial failure on some of the items, you want to check that if you have 5 items and 2 failures the callback is only called twice, for example?

2024-10-02 19:29 UTC, kellen-miller commented
> I think there's still a test missing for partial failure on some of the items, you want to check that if you have 5 items and 2 failures the callback is only called twice, for example?

I think this unit test earlier in the file already covers that?
https://github.com/kellen-miller/opensearch-go/blob/bugfix/execute-item-fail-callbacks-bulk-error/opensearchutil/bulk_indexer_internal_test.go#L277

Specifically this check here:
https://github.com/kellen-miller/opensearch-go/blob/bugfix/execute-item-fail-callbacks-bulk-error/opensearchutil/bulk_indexer_internal_test.go#L391-L398

I might be misunderstanding though, I'm happy to add more if that's not the test case you're referring too.

2024-10-02 20:15 UTC, dblock commented
> I might be misunderstanding though, I'm happy to add more if that's not the use case you're referring too.

First, thank you for hanging in here with me ;)

The old code did not call `item.OnFailure(ctx, item, info, err)` in this scenario at all, but did increment the number of fails (and then that was tested). So those tests with only some item callbacks also should check how many times `item.OnFailure(ctx, item, info, err)` has been invoked and that it was invoked with all the right items.

Without trying, some examples where I think all tests pass but the code is broken: call `item.OnFailure(ctx, **the first item every time**, info, err)`. With first 2/5 items failing call `onFailure` 5 times.

2024-10-02 20:53 UTC, kellen-miller commented
> The old code did not call item.OnFailure(ctx, item, info, err) in this scenario at all, but did increment the number of fails (and then that was tested). So those tests with only some item callbacks also should check how many times item.OnFailure(ctx, item, info, err) has been invoked and that it was invoked with all the right items.

> Without trying, some examples where I think all tests pass but the code is broken: call item.OnFailure(ctx, **the first item every time**, info, err). Or, with first 2/5 items failing call onFailure 5 times.

Ah gotcha gotcha, sorry for some much back and forth 😄.  Let me update the other tests to check for this.

2024-10-02 21:16 UTC, dblock commented
> Ah gotcha gotcha, sorry for some much back and forth 😄. Let me update the other tests to check for this.

No stress! I enjoy this type of conversations because I am super [OCD about tests](https://github.com/apache/lucene/pull/711#issuecomment-1055853457) :)

2024-10-03 18:24 UTC, dblock approved these changes
👏

2024-10-03 18:24 UTC, merged

2024-10-04 13:48 UTC, kellen-miller commented
@dblock sorry to bother again! Is there any roadmap or release cadence to this library? Just wondering when the release process with my fix will happen. I can always target `@main` in the mean time, just like to have tagged version set.

2024-10-04 14:30 UTC, dblock commented
Open a "release v. Next" issue and we'll take care of it quickly.